language: node_js

node_js:
  - 9.11.1 
  
branches:
  only:
    - master

integrations:
  hub:
    - integrationName: manishas_personal_dh
      type: dockerRegistryLogin

build:
  ci:
    - >
      if [ "$JOB_TRIGGERED_BY_NAME" = "nightly_trigger" ]; then
        docker build -t manishas/nightlyimage:latest --build-arg IMAGE=readytalk/nodejs --build-arg TAG=latest . &&
        docker push manishas/nightlyimage:latest;
      fi;

    - >
      if [ "$JOB_TRIGGERED_BY_NAME" != "nightly_trigger" ]; then
        docker build -t manishas/node_app_img:latest --build-arg IMAGE=manishas/nightlyimage --build-arg TAG=latest . &&
        docker push manishas/node_app_img:latest;
      fi;

resources:
  - name: nightly_trigger
    type: time
    versionTemplate:
      interval: "0 0 * * *"

jobs:
  - name: faster_docker_build_npm_runCI
    type: runCI
    steps:
      - IN: nightly_trigger
